# Generated by Django 3.2.7 on 2022-06-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='berhil',
        ),
        migrations.DeleteModel(
            name='hawara',
        ),
    ]
