# Generated by Django 3.2.7 on 2022-06-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personne',
        ),
        migrations.DeleteModel(
            name='Personne2',
        ),
    ]
