# Generated by Django 4.1 on 2022-08-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0002_auto_20220616_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticide_aoulouz',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pesticide_bananier1',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pesticide_bananier2',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pesticide_benmbark',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pesticide_berhil',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pesticide_drisse',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pesticide_lglidi',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pesticide_mariem',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pesticide_maryem2',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pesticide_raisin',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pesticide_rgaigue',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pesticide_zbirate',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
