# Generated by Django 4.1 on 2022-08-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0003_alter_pesticide_aoulouz_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticide_aoulouz',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_bananier1',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_bananier2',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_benmbark',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_berhil',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_drisse',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_lglidi',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_mariem',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_maryem2',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_raisin',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_rgaigue',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_zbirate',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
