# Generated by Django 4.1 on 2022-08-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0005_alter_pesticide_aoulouz_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticide_aoulouz',
            name='time',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pesticide_bananier1',
            name='time',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pesticide_bananier2',
            name='time',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pesticide_benmbark',
            name='time',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pesticide_berhil',
            name='time',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pesticide_drisse',
            name='time',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pesticide_lglidi',
            name='time',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pesticide_mariem',
            name='time',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pesticide_maryem2',
            name='time',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pesticide_raisin',
            name='time',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pesticide_rgaigue',
            name='time',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pesticide_zbirate',
            name='time',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
