# Generated by Django 4.1 on 2022-08-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0006_pesticide_aoulouz_time_pesticide_bananier1_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticide_aoulouz',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pesticide_bananier1',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pesticide_bananier2',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pesticide_benmbark',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pesticide_berhil',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pesticide_drisse',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pesticide_lglidi',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pesticide_mariem',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pesticide_maryem2',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pesticide_raisin',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pesticide_rgaigue',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pesticide_zbirate',
            name='time',
        ),
    ]
