# Generated by Django 4.1 on 2022-08-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0011_engrais_aoulouz_user_engrais_bananier1_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engrais_aoulouz',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engrais_bananier1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engrais_bananier2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engrais_benmbark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engrais_berhil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engrais_drisse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engrais_lglidi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engrais_mariem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engrais_maryem2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engrais_raisin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engrais_rgaigue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engrais_zbirate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pesticide_aoulouz',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pesticide_bananier1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pesticide_bananier2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pesticide_benmbark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pesticide_berhil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pesticide_drisse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pesticide_lglidi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pesticide_mariem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pesticide_maryem2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pesticide_raisin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pesticide_rgaigue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pesticide_zbirate',
            name='user',
        ),
    ]
