# Generated by Django 4.1 on 2022-08-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0012_remove_engrais_aoulouz_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticide_aoulouz',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_aoulouz',
            name='groupe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_bananier1',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_bananier1',
            name='groupe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_bananier2',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_bananier2',
            name='groupe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_benmbark',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_benmbark',
            name='groupe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_berhil',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_berhil',
            name='groupe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_drisse',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_drisse',
            name='groupe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_lglidi',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_lglidi',
            name='groupe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_mariem',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_mariem',
            name='groupe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_maryem2',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_maryem2',
            name='groupe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_raisin',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_raisin',
            name='groupe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_rgaigue',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_rgaigue',
            name='groupe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_zbirate',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pesticide_zbirate',
            name='groupe',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
