# Generated by Django 4.1 on 2022-08-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0013_pesticide_aoulouz_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticide_aoulouz',
            name='category',
            field=models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movinto', 'Movinto'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide_aoulouz',
            name='destination',
            field=models.CharField(blank=True, choices=[('od berhil', 'od berhil'), ('od driss', 'od driss'), ('aoulouz', 'aoulouz'), ('meryem 1', 'meryem 1'), ('meryem 2', 'meryem 2'), ('plombier', 'plombier'), ('zbirate ', 'zbirate '), ('raisinier ', 'raisinier '), ('lglidi ', 'lglidi '), ('benmbrek/jkini/mhijib', 'benmbrek/jkini/mhijib'), ('bananier 1', 'bananier 1'), ('bananier 2', 'bananier 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_bananier1',
            name='category',
            field=models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movinto', 'Movinto'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide_bananier1',
            name='destination',
            field=models.CharField(blank=True, choices=[('od berhil', 'od berhil'), ('od driss', 'od driss'), ('aoulouz', 'aoulouz'), ('meryem 1', 'meryem 1'), ('meryem 2', 'meryem 2'), ('plombier', 'plombier'), ('zbirate ', 'zbirate '), ('raisinier ', 'raisinier '), ('lglidi ', 'lglidi '), ('benmbrek/jkini/mhijib', 'benmbrek/jkini/mhijib'), ('bananier 1', 'bananier 1'), ('bananier 2', 'bananier 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_bananier2',
            name='category',
            field=models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movinto', 'Movinto'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide_bananier2',
            name='destination',
            field=models.CharField(blank=True, choices=[('od berhil', 'od berhil'), ('od driss', 'od driss'), ('aoulouz', 'aoulouz'), ('meryem 1', 'meryem 1'), ('meryem 2', 'meryem 2'), ('plombier', 'plombier'), ('zbirate ', 'zbirate '), ('raisinier ', 'raisinier '), ('lglidi ', 'lglidi '), ('benmbrek/jkini/mhijib', 'benmbrek/jkini/mhijib'), ('bananier 1', 'bananier 1'), ('bananier 2', 'bananier 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_benmbark',
            name='category',
            field=models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movinto', 'Movinto'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide_benmbark',
            name='destination',
            field=models.CharField(blank=True, choices=[('od berhil', 'od berhil'), ('od driss', 'od driss'), ('aoulouz', 'aoulouz'), ('meryem 1', 'meryem 1'), ('meryem 2', 'meryem 2'), ('plombier', 'plombier'), ('zbirate ', 'zbirate '), ('raisinier ', 'raisinier '), ('lglidi ', 'lglidi '), ('benmbrek/jkini/mhijib', 'benmbrek/jkini/mhijib'), ('bananier 1', 'bananier 1'), ('bananier 2', 'bananier 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_berhil',
            name='category',
            field=models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movinto', 'Movinto'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide_berhil',
            name='destination',
            field=models.CharField(blank=True, choices=[('od berhil', 'od berhil'), ('od driss', 'od driss'), ('aoulouz', 'aoulouz'), ('meryem 1', 'meryem 1'), ('meryem 2', 'meryem 2'), ('plombier', 'plombier'), ('zbirate ', 'zbirate '), ('raisinier ', 'raisinier '), ('lglidi ', 'lglidi '), ('benmbrek/jkini/mhijib', 'benmbrek/jkini/mhijib'), ('bananier 1', 'bananier 1'), ('bananier 2', 'bananier 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_drisse',
            name='category',
            field=models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movinto', 'Movinto'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide_drisse',
            name='destination',
            field=models.CharField(blank=True, choices=[('od berhil', 'od berhil'), ('od driss', 'od driss'), ('aoulouz', 'aoulouz'), ('meryem 1', 'meryem 1'), ('meryem 2', 'meryem 2'), ('plombier', 'plombier'), ('zbirate ', 'zbirate '), ('raisinier ', 'raisinier '), ('lglidi ', 'lglidi '), ('benmbrek/jkini/mhijib', 'benmbrek/jkini/mhijib'), ('bananier 1', 'bananier 1'), ('bananier 2', 'bananier 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_lglidi',
            name='category',
            field=models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movinto', 'Movinto'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide_lglidi',
            name='destination',
            field=models.CharField(blank=True, choices=[('od berhil', 'od berhil'), ('od driss', 'od driss'), ('aoulouz', 'aoulouz'), ('meryem 1', 'meryem 1'), ('meryem 2', 'meryem 2'), ('plombier', 'plombier'), ('zbirate ', 'zbirate '), ('raisinier ', 'raisinier '), ('lglidi ', 'lglidi '), ('benmbrek/jkini/mhijib', 'benmbrek/jkini/mhijib'), ('bananier 1', 'bananier 1'), ('bananier 2', 'bananier 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_mariem',
            name='category',
            field=models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movinto', 'Movinto'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide_mariem',
            name='destination',
            field=models.CharField(blank=True, choices=[('od berhil', 'od berhil'), ('od driss', 'od driss'), ('aoulouz', 'aoulouz'), ('meryem 1', 'meryem 1'), ('meryem 2', 'meryem 2'), ('plombier', 'plombier'), ('zbirate ', 'zbirate '), ('raisinier ', 'raisinier '), ('lglidi ', 'lglidi '), ('benmbrek/jkini/mhijib', 'benmbrek/jkini/mhijib'), ('bananier 1', 'bananier 1'), ('bananier 2', 'bananier 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_maryem2',
            name='category',
            field=models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movinto', 'Movinto'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide_maryem2',
            name='destination',
            field=models.CharField(blank=True, choices=[('od berhil', 'od berhil'), ('od driss', 'od driss'), ('aoulouz', 'aoulouz'), ('meryem 1', 'meryem 1'), ('meryem 2', 'meryem 2'), ('plombier', 'plombier'), ('zbirate ', 'zbirate '), ('raisinier ', 'raisinier '), ('lglidi ', 'lglidi '), ('benmbrek/jkini/mhijib', 'benmbrek/jkini/mhijib'), ('bananier 1', 'bananier 1'), ('bananier 2', 'bananier 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_raisin',
            name='category',
            field=models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movinto', 'Movinto'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide_raisin',
            name='destination',
            field=models.CharField(blank=True, choices=[('od berhil', 'od berhil'), ('od driss', 'od driss'), ('aoulouz', 'aoulouz'), ('meryem 1', 'meryem 1'), ('meryem 2', 'meryem 2'), ('plombier', 'plombier'), ('zbirate ', 'zbirate '), ('raisinier ', 'raisinier '), ('lglidi ', 'lglidi '), ('benmbrek/jkini/mhijib', 'benmbrek/jkini/mhijib'), ('bananier 1', 'bananier 1'), ('bananier 2', 'bananier 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_rgaigue',
            name='category',
            field=models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movinto', 'Movinto'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide_rgaigue',
            name='destination',
            field=models.CharField(blank=True, choices=[('od berhil', 'od berhil'), ('od driss', 'od driss'), ('aoulouz', 'aoulouz'), ('meryem 1', 'meryem 1'), ('meryem 2', 'meryem 2'), ('plombier', 'plombier'), ('zbirate ', 'zbirate '), ('raisinier ', 'raisinier '), ('lglidi ', 'lglidi '), ('benmbrek/jkini/mhijib', 'benmbrek/jkini/mhijib'), ('bananier 1', 'bananier 1'), ('bananier 2', 'bananier 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticide_zbirate',
            name='category',
            field=models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movinto', 'Movinto'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pesticide_zbirate',
            name='destination',
            field=models.CharField(blank=True, choices=[('od berhil', 'od berhil'), ('od driss', 'od driss'), ('aoulouz', 'aoulouz'), ('meryem 1', 'meryem 1'), ('meryem 2', 'meryem 2'), ('plombier', 'plombier'), ('zbirate ', 'zbirate '), ('raisinier ', 'raisinier '), ('lglidi ', 'lglidi '), ('benmbrek/jkini/mhijib', 'benmbrek/jkini/mhijib'), ('bananier 1', 'bananier 1'), ('bananier 2', 'bananier 2')], max_length=100),
        ),
    ]
